<!DOCTYPE html>
<html lang="zh-Hant-TW">

<head>
    <!-- Google tag (gtag.js) -->
    <script defer src="https://www.googletagmanager.com/gtag/js?id=G-HSTC1XDRQY"></script>
    <script defer>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-HSTC1XDRQY');
    </script>
    <!-- 網頁標頭 -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta http-equiv="Content-Language" content="zh-tw">   
    <meta name="author" content="優美紙品設計有限公司">

    <meta name="robots" content="index,follow"/>
    <meta name="google" content="index,follow"/>
    <meta name="googlebot" content="index,follow"/>
    <meta name="verify" content="index,follow"/>

    <title>優美紙品設計有限公司</title>
    <!-- seo設定 -->
    <meta name="keywords" content="各式紙類批發,桃園紙類設計,批發美術用紙,進口美術紙,珍珠紙,珠光紙,包裝紙,七彩夢幻珍珠紙,特亮珠光紙,夢幻珍珠紙,活力紙,優美">
    <meta name="url" content="https://you-mei-paper.com/">
    <meta name="description" content="專門生產美術紙的優美紙業，批發美術用紙、進口美術紙、珍珠紙、珠光紙、包裝紙等美術紙給紙類經銷商及包裝和紙盒工廠，優美紙業的珍珠紙更有多樣選擇：七彩夢幻珍珠紙、特亮珠光紙、夢幻珍珠紙、活力紙，優質的美術用紙批發可供國內、外廠商對美術紙的需求，並要求紙品的色系及細緻加工度，也可因應您對於美術用紙的客制化要求。">
    <meta name="company" content="優美紙品設計有限公司">
    <meta name="copyright" content="優美紙品設計有限公司">
    <meta name="mobile-web-app-capable" content="yes">

    <meta property="og:site_name" content="各式紙類批發∣優美紙品設計有限公司"/>
    <meta property="og:type" content="website"/>
    <meta property="og:url" content="https://you-mei-paper.com/">
    <meta property="og:title" content="桃園紙類設計 | 優美紙品設計有限公司｜桃園紙商｜批發美術用紙 | 七彩夢幻珍珠 | 特亮珠光紙"> 
    <meta property="og:description" content="專門生產美術紙的優美紙業，批發美術用紙、進口美術紙、珍珠紙、珠光紙、包裝紙等美術紙給紙類經銷商及包裝和紙盒工廠，優美紙業的珍珠紙更有多樣選擇：七彩夢幻珍珠紙、特亮珠光紙、夢幻珍珠紙、活力紙，優質的美術用紙批發可供國內、外廠商對美術紙的需求，並要求紙品的色系及細緻加工度，也可因應您對於美術用紙的客制化要求。"> 

<body>
    <!-- 背景圖 -->
    <body background="images/about_bg.png">
    <!-- Google Tag Manager (noscript) -->
    <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PGZ3KCD" height="0" width="0" style="display:none;visibility:hidden">
        </iframe>
    </noscript>
    <!-- End Google Tag Manager (noscript) -->
    <div class="wrapper">
        

<div class="main-mask"></div>
<!-- 導覽列 -->
<header id="header" class="fixed-top">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-sm-10 col-12">
                <div class="menu-box" style=text-align:center;>
                    <div class="menu-flex">
                        <div class="header_logo">
                            <a class="d-block" href="index.html">
                                <span class="pl-1" style="font-size: 30px;">優美紙品設計有限公司</span>
                            </a>
                        </div>
                        <div class="bar-btn d-lg-none d-block">
                            <div class="bar"></div>
                        </div>            
                    </div>
                    <nav class="menu-nav" style="text-align:center;">
                        <ul class="menu-item pb-lg-0 pb-3">
                            <li class="menu-list">
                                <a style="font-size: 20px;" href="index.html">首頁</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                <a style="font-size: 20px;" href="#footer1"class="contact-link">樣品展示</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                <a style="font-size: 20px;" href="#footer2"class="contact-link">聯絡我們</a>&nbsp;&nbsp;&nbsp;&nbsp;
                                <a style="font-size: 20px;" href="#footer3" class="contact-link">服務項目</a>
                            </li>
                        </ul>
                    </nav>
            </div>
        </div>
    </div>
</header>     
            <!-- 公司介紹 -->
            <div class="container-fluid">
                <div class="row justify-content-center align-items-center h-100">
                    <div class="col-12">
                        <div class="index-banner">
                            <div class="row justify-content-center">
                                <div class="col-7 text-center">
                                    <div class="web-title text-cente">
                                        <h2 class="h2" style="font-size :30px;color: black">公司簡介</h2>
                                    </div>
                                    <p class="py-3" style="font-size :20px;color: black">
                                        專門生產美術紙的優美紙業，批發美術用紙、進口美術紙、珍珠紙、珠光紙、包裝紙等美術紙給紙類經銷商及包裝和紙盒工廠，優美紙業的珍珠紙更有多樣選擇：七彩夢幻珍珠紙、特亮珠光紙、夢幻珍珠紙、活力紙，優質的美術用紙批發可供國內、外廠商對美術紙的需求，並要求紙品的色系及細緻加工度，也可因應您對於美術用紙的客制化要求。                             
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-12">  
                        <div class="case-box bg-light">
                            
<footer id="footer1">
                            <div class="web-title text-center">
                                <h2 class="h2">樣品展示</h2>
                            </div>
                            <div style="display: inline-flex;">
                                <div>
                                    <img src="images/10074.jpg" alt="雲彩紙" class="img-fluid" style="width: 70%; height: 70%"> <!-- 改大小 -->
                                    <div class="inner-box">
                                        <h4 class="h4 text-white font-weight-bold mb-3" title="雲彩紙">雲彩紙</h4>
                                    </div>
                                </div>
                                <div>
                                    <img src="images/10075.jpg" alt="丹迪紋" class="img-fluid" style="width: 70%; height: 70%"> <!-- 改大小 -->
                                    <div class="inner-box">
                                        <h4 class="h4 text-white font-weight-bold mb-3" title="雲彩紙">雲彩紙</h4>
                                        
                                    </div>
                                </div>
                                <div>
                                    <img src="images/10081.jpg" alt="特亮珠光紙" class="img-fluid" style="width: 70%; height: 70%"> <!-- 改大小 --> 
                                    <div class="inner-box">
                                        <h4 class="h4 text-white font-weight-bold mb-3" title="雲彩紙">雲彩紙</h4>
                                        
                                    </div>
                                </div>
                                <div>
                                    <img src="images/10088.jpg" alt="七彩夢幻紙" class="img-fluid" style="width: 70%; height: 70%"> <!-- 改大小 -->
                                    <div class="inner-box">
                                        <h4 class="h4 text-white font-weight-bold mb-3" title="雲彩紙">雲彩紙</h4>
                                        
                                    </div>
                                </div>
                            </div>
                        </footer>
                            <!-- <div class="owl-carousel owl-theme">
                                <div class="item case-item">
                                        <img src="images/10074.jpg" alt="雲彩紙" class="img-fluid" style="width: 40%; height: 40%">
                                        <h4 class="d-block d-md-none case-title text-dark-yellow font-weight-bold mt-2">雲彩紙</h4>
                                        <div class="mask-case d-none d-md-flex align-items-center justify-content-center">
                                            <div class="inner-box">
                                                <h4 class="h4 text-white font-weight-bold mb-3" title="雲彩紙">雲彩紙</h4>
                                                
                                            </div>
                                        </div>                            
                                    </a>
                                </div>
                                <div class="item case-item">
                                    <img src="images/10075.jpg" alt="丹迪紋" class="img-fluid" style="width: 40%; height: 40%">
                                    <h4 class="d-block d-md-none case-title text-dark-yellow font-weight-bold mt-2">丹迪紋</h4>
                                    <div class="mask-case d-none d-md-flex align-items-center justify-content-center">
                                        <div class="inner-box">
                                            <h4 class="h4 text-white font-weight-bold mb-3" title="丹迪紋">丹迪紋</h4>
                                            
                                        </div>
                                    </div>                            
                                </div>
                                <div class="item case-item">
                                    <img src="images/10081.jpg" alt="特亮珠光紙" class="img-fluid" style="width: 40%; height: 40%">
                                    <h4 class="d-block d-md-none case-title text-dark-yellow font-weight-bold mt-2">特亮珠光紙</h4>
                                    <div class="mask-case d-none d-md-flex align-items-center justify-content-center">
                                        <div class="inner-box">
                                            <h4 class="h4 text-white font-weight-bold mb-3" title="特亮珠光紙">特亮珠光紙</h4>
                                            
                                        </div>
                                    </div>                            
                                </div>
                                <div class="item case-item">
                                    <img src="images/10088.jpg" alt="七彩夢幻紙" class="img-fluid" style="width: 40%; height: 40%">
                                    <h4 class="d-block d-md-none case-title text-dark-yellow font-weight-bold mt-2">七彩夢幻紙</h4>
                                    <div class="mask-case d-none d-md-flex align-items-center justify-content-center">
                                        <div class="inner-box">
                                            <h4 class="h4 text-white font-weight-bold mb-3" title="七彩夢幻紙">七彩夢幻紙</h4>
                                            
                                        </div>
                                    </div>                            
                                </div>
                            </div>  -->
                        </div> 
                        <!-- 服務內容 -->
                        <div class="index-service index-service-bg">
                            <div>
                                <footer id="footer3">
                                <div class="web-title text-center">
                                    <h2 class="h2 text-light text-down">服務項目</h2>
                                </div>
                                <div>
                                    <h4 class="h4 index-service-title my-4" title="紅包袋設計" style="color: black; text-align:center;">1. 紅包袋設計</h4>
                                    <h4 class="h4 index-service-title my-4" title="色卡印刷" style="color: black; text-align:center;">2. 色卡印刷</h4>
                                    <h4 class="h4 index-service-title my-4" title="紙卡販售" style="color: black; text-align:center;">3. 紙卡販售</h4>
                                    <h4 class="h4 index-service-title my-4" title="美術紙製造" style="color: black; text-align:center;">4. 美術紙製造</h4>
                                    <h4 class="h4 index-service-title my-4" title="" style="color: black; text-align:center;"></h4>
                                    <h4 class="h4 index-service-title my-4" title="" style="color: black; text-align:center;"></h4>
                                    <h4 class="h4 index-service-title my-4" title="" style="color: black; text-align:center;"></h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
        <!-- 公司位置 -->
<div class="container-fluid">
    <div class="row justify-content-center my-5">
        <div class="col-12">
            <div class="contact-wrap contact-bg">
                <div class="">
                    <div class="web-title text-center">
                        <h2 id="contact" class="h2 text-light text-down " >公司位置</h2>
                    </div>
                    <div class="row justify-content-center text-light">
                        <h2 class="col-10 font-weight-bold text-center mb-4 contact-text">
                            歡迎直接來電詢問 
                            <span ><a  class="text-danger"  href="tel:+886-3-3817997" style="font-size: 20px;">03-3817997</a></span>
                        </h2>
                       <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3615.4059521375907!2d121.2350196!3d25.020293900000002!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3468204b6e67d96b%3A0x2445fe620a73ddbd!2zMzM35qGD5ZyS5biC5aSn5ZyS5Y2A5LqU6Z2S6LevMjAx6Jmf!5e0!3m2!1szh-TW!2stw!4v1665238660415!5m2!1szh-TW!2stw" width="100%" height="500" style="border: 10px;;" allowfullscreen="true" loading="lazy"></iframe>
                    </div>
                    
                    <div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- <footer id="footer2">
 <div style="display: inline-flex;">
                                <div>
                                    <img src="images/10074.jpg" alt="雲彩紙" class="img-fluid" style="width: 70%; height: 70%"> 
                                    <div class="inner-box">
                                        <h4 class="h4 text-white font-weight-bold mb-3" title="雲彩紙">雲彩紙</h4>
                                    </div>
                                </div>
                                <div>
                                    <img src="images/10075.jpg" alt="丹迪紋" class="img-fluid" style="width: 70%; height: 70%"> 
                                    <div class="inner-box">
                                        <h4 class="h4 text-white font-weight-bold mb-3" title="雲彩紙">雲彩紙</h4>
                                        
                                    </div>
                                </div>
                                <div>
                                    <img src="images/10081.jpg" alt="特亮珠光紙" class="img-fluid" style="width: 70%; height: 70%"> 
                                        <h4 class="h4 text-white font-weight-bold mb-3" title="雲彩紙">雲彩紙</h4>
                                        
                                    </div>
                                </div>
                                <div>
                                    <img src="images/10088.jpg" alt="七彩夢幻紙" class="img-fluid" style="width: 70%; height: 70%"> 
                                    <div class="inner-box">
                                        <h4 class="h4 text-white font-weight-bold mb-3" title="雲彩紙">雲彩紙</h4>
                                        
                                    </div>
                                </div>
                            </div>
</footer> -->
<!-- 頁尾公司聯絡方式 -->
<footer id="footer2">
    
    <div class="footer-list" id="footer_contact">
        <h5 class="footer-title">優美紙品設計有限公司</h5>
        <ul>
            <li>桃園公司</li>
            <li>桃園市大園區五權里五青路201號</li>
            <li>台南工廠</li>
            <li>台南市安平工業區新樂路45號</li>
            <li>電話 : <a style="color:white" href="tel:+886-3-3817997">(03)-3817997<a></li>
            <li><a style="color:white" href="tel:+886-3-3815628">傳真 : (03)-3815628</a></li>
        </ul>
    </div>
    <div class="copyright">
        <p class="small text-center d-block text-gray font-weight-bold">
            Copyright © <script>document.write(new Date().getFullYear())</script>優美紙品設計有限公司 | All Rights Reserved
        </p>
    </div>
</footer>

<div class="web-top" title="回到頂部">
    <i class="fas fa-chevron-up fa-w-18"></i>
</div>

</body>

</html>
